name: Build & Deploy AMI with packer


on:
  pull_request:
    branches: [ main ]
    types: [ closed ] 

  workflow_dispatch:

jobs:
  packer:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

       
      - name: Validate Template 
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-syntax-only"
          target: ami.pkr.hcl

      - name: Build Artifact with Maven
        run: |
          mvn clean install -DskipTests 
          
      - name: Build Ami
        run: |
          ls
          packer init .
          packer build -on-error=abort -force -var aws_access_key=${{secrets.AWS_ACCESS_KEY}} -var aws_secret_key=${{secrets.AWS_SECRET_KEY}} -var S3_aws_access_key=${{secrets.S3_AWS_ACCESS_KEY}} -var S3_aws_secret_key=${{secrets.S3_AWS_SECRET_KEY}} ami.pkr.hcl
        env:
            AWS_ACCESS_KEY : ${{secrets.AWS_ACCESS_KEY}}
            AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
            S3_AWS_ACCESS_KEY: ${{secrets.S3_AWS_ACCESS_KEY}}
            S3_AWS_SECRET_KEY: ${{secrets.S3_AWS_SECRET_KEY}}
            PACKER_LOG: 1

      
      