name: Build & Deploy AMI with packer


on:
  pull_request:
    branches: [ main ]
    types: [ closed ] 

  workflow_dispatch:


jobs:
  packer:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

       
      - name: Validate Template 
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: "-syntax-only -var aws_access_key=1 -var aws_secret_key=2"
          target: ami.pkr.hcl

      - name: Build Ami with .jar App
        run: |
          mvn clean install -DskipTests 
          packer init .
          packer build -on-error=abort -force -var aws_access_key=${{secrets.AWS_ACCESS_KEY}} -var aws_secret_key=${{secrets.AWS_SECRET_KEY}} -var webservice=./0.0.1-SNAPSHOT/webservice-0.0.1-SNAPSHOT.jar ami.pkr.hcl
        env:
            AWS_ACCESS_KEY : ${{secrets.AWS_ACCESS_KEY}}
            AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
            PACKER_LOG: 1

      
      