name: Require pull request reviews before merging

# Controls when the workflow will run
on: 
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Unit Test
      run : |
        echo run unit-test

    - name: Validate Template 
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: "-syntax-only"
        target: ami.pkr.hcl