name: Require pull request reviews before merging

# Controls when the workflow will run
on: 
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: 
  ci_cd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - name: Build with Maven(Unit Test)
      run : echo run unit-test
            ls
            pwd
            cmd
      #mvn clean install